### ISSUE TITLE
FATAL ERROR: creating loader: unable to remap stdios, FD 257 is already in use

### ISSUE THREAD

**Issue by thundergolfer** [google/gvisor#10232]
### Description

Recently we've been experiencing an elevated level of flakes in our Github Actions workflows. From application logs it was apparent that the issue was gVisor containers failing to start up. I have interested runsc debug log archiving into the affected workflow to help track down why this is happening. 

```yaml
      - name: Archive runtime debug logs
        if: (matrix.runtime == 'gvisor') && (success() || failure())
        uses: actions/upload-artifact@v3
        with:
          name: runtime-debug-logs
          path: /tmp/runsc/
          if-no-files-found: warn
```

Today I found this interesting error in the debug logs.

```
FATAL ERROR: creating loader: unable to remap stdios, FD 257 is already in use
```

I have attached the full `boot.txt` logs below 🙂. 

**Github Runner Information:**

```
Runner group: [Default](https://github.com/organizations/modal-labs/settings/actions/runner-groups/1)
Size:
8-cores · 32 GB RAM · 300 GB SSD
Public IP: Disabled
Image source: GitHub-hosted
Image name: Ubuntu 20.04
```

**Further context:**

The Github Actions workflow is running a job which does `sudo -E PATH=$PATH cargo test ...` and these Cargo tests run a number of container runtime tests concurrently, each using `runsc run`, `runsc checkpoint`, and `runsc restore`. 

### runsc version

We're using https://github.com/google/gvisor/commit/6ad1af2b9cbfe5404c1cd7fd3fef5bd55a791955. 

### kubectl (if using Kubernetes)

N/A

### repo state (if built from source)

We're using https://github.com/google/gvisor/commit/6ad1af2b9cbfe5404c1cd7fd3fef5bd55a791955. 

### runsc debug logs (if available)

[runsc.log.20240331-181159.853300.run.txt](https://github.com/google/gvisor/files/14817328/runsc.log.20240331-181159.853300.run.txt)

[boot.txt](https://github.com/google/gvisor/files/14817339/boot.txt)
