### ISSUE TITLE
k8s Pod should get OOMKilled but does not

### ISSUE THREAD

**Issue by 0xB1a60** [google/gvisor#10980]
### Description

Hello gVisor team,

I am observing some strange behavior and was hoping you could clarify whether this is expected or if there might be an issue with my setup.

I am deliberately starting a pod that should be OOMKilled, but under gVisor, it is not.

Thank you for your time

### Steps to reproduce

1. Install k3s and gVisor https://gist.github.com/Frichetten/c77ee24b12edd2ab852738fc8221a1f1
2. Without gVisor - Pod gets immediately killed with OOMKilled
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
spec:
  restartPolicy: Never
  containers:
  - name: memory-demo-2-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
```

3. With gVisor - Pod works fine , you can even increase --vm-bytes to bigger value (if your system allows it) and it will still not get OOMKilled
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
spec:
  restartPolicy: Never
  runtimeClassName: gvisor
  containers:
  - name: memory-demo-2-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
```

### runsc version

```shell
runsc version release-20240923.0
spec: 1.1.0-rc.1
```

### uname

Linux REDACTED 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### kubectl (if using Kubernetes)

```shell
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.5+k3s1", GitCommit:"9b586704a211264ca86b22f2a0b4617b00412235", GitTreeState:"clean", BuildDate:"2024-09-19T23:32:01Z", GoVersion:"go1.22.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.30) exceeds the supported minor version skew of +/-1


NAME            STATUS   ROLES                  AGE   VERSION
REDACTED   Ready    control-plane,master   8h    v1.30.5+k3s1
```
