### ISSUE TITLE
tektonTask git-credentialscontainer stuck in "initializing" state

### ISSUE THREAD

**Issue by gattytto** [google/gvisor#2233]
Hello, I'm using gVisor for a TaskRun in Tekton.

the taskRun fetches a private git repo and compiles some code. 

the git credentials init takes place in "initContainers:" first container to run in the pod. 

here is the relevant piece of logs that throws the error:
````
D0323 05:50:11.651647       1 fsgofer.go:290] Attempt 0 to open file failed, mode: 0xa0800, path: "/tekton/creds-secrets/basic-user-pass/username", err: too many levels of symbolic links

D0323 05:50:11.653856       1 fsgofer.go:290] Attempt 0 to open file failed, mode: 0xa0800, path: "/tekton/creds-secrets/basic-user-pass/password", err: too many levels of symbolic links

D0323 05:50:11.652274       1 fsgofer.go:290] Attempt 0 to open file failed, mode: 0xa0800, path: "/tekton/creds-secrets/basic-user-pass/..data", err: too many levels of symbolic links
````

here is the full logs:
https://raw.githubusercontent.com/gattytto/envfiles/master/gvisor-debug.log

**Comment by prattmic** [comment]
What is the actual error that the application fails with? i.e., are we certain the symlink error is the root cause of failure?

To help track this down, could you also enable strace logging in addition to debug logging? (Add `--strace` to the runsc args; https://gvisor.dev/docs/user_guide/debugging/).

**Comment by gattytto** [comment]
@prattmic no errors in the container, held at "initializing" state
````yaml
initContainerStatuses:
  - containerID: cri-o://30b6f9f5542663780bf4b876882cfad783bff6d0b90f288abc0779ac4bbaf4ef
    image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init@sha256:af3db1677ca1bfd3b3927b98b7cd11fd0226c7f8646d805a868148bf266d4d01
    imageID: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init@sha256:af3db1677ca1bfd3b3927b98b7cd11fd0226c7f8646d805a868148bf266d4d01
    lastState: {}
    name: credential-initializer
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: "2020-03-24T19:20:41Z"
````
here's the full pod yaml:
https://raw.githubusercontent.com/gattytto/envfiles/master/taskrun-pod.yaml

and the log with strace: 
https://raw.githubusercontent.com/gattytto/envfiles/master/runsc-debug-trace.log
