### ISSUE TITLE
Console/PTY settings ignored on container level

### ISSUE THREAD

**Issue by lorenz** [google/gvisor#2714]
**Description**
If the sandbox is created without a console socket because the first container/task does not have `Terminal: true`, subsequent containers created in that sandbox don't create master/slave sockets for the PTY leading to the shim timing out because it can't receive a TTY. This is particularly bad on K8s since containerd/CRI always creates the first container as a pause container so you cannot get a TTY.

**Steps to reproduce**

Run Kubernetes with containerd/CRI (standard setup with V2 shim), then run `kubectl run -ti --image busybox` and see that it fails to ever acquire a TTY. If only `-i` is used, it succeeds (but is missing the TTY).

**Environment**

Please include the following details of your environment:

Fully custom environment based on `release-20200323.0`.

**Comment by fvoznika** [comment]
TTY handling is missing from ContainerManager.Start. Stdios are imported as non-console [here](https://github.com/google/gvisor/blob/05c89af6edde6158844d4debfe68bc598fec4418/runsc/boot/loader.go#L731).

Here's a pod to repro:
```
apiVersion: v1
kind: Pod
metadata:
  name: term
spec:
  runtimeClassName: gvisor
  containers:
  - name: main
    image: alpine
    stdin: true
    tty: true
```

Fails with:
```
  Warning  Failed     22m (x6 over 35m)     kubelet, gke-gvisor-1-15-gvisor-56a73b86-c1zp  Error: context deadline exceeded
```
