### ISSUE TITLE
StatFS exposing unexpected implementation detail

### ISSUE THREAD

**Issue by lorenz** [google/gvisor#3339]
**Description**
When running Kubernetes CTS on gVisor, all tmpfs-related tests fail because the reported filesystem type (by the statfs family of syscalls) is V9FS_MAGIC, not TMPFS_MAGIC as the test suite is expecting. For a userland application running in gVisor this is unexpected as all mount information exposed to it (via procfs) uses the underlying mount information from the host system, but statfs basically leaks an implementation detail from gVisor to the application.
The problem is [here](
https://github.com/google/gvisor/blob/6722b1e56fa63f3409f222a63241705aa3f3ace4/pkg/sentry/fs/gofer/inode.go#L677) where the magic value gets hardcoded. This would either need to be propagated by the sentry over P9 (would mean a protocol extension) or overwritten based on the mounting information known to gVisor.

**Steps to reproduce**

This creates a pod on a K8s cluster which runs the test which is failing on gVisor.
```
apiVersion: v1
kind: Namespace
metadata:
  name: conformance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: conformance
  name: conformance-serviceaccount
  namespace: conformance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: conformance
  name: conformance-serviceaccount-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conformance-serviceaccount
subjects:
- kind: ServiceAccount
  name: conformance-serviceaccount
  namespace: conformance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    component: conformance
  name: conformance-serviceaccount
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '/metrics'
  - '/logs'
  - '/logs/*'
  verbs:
  - 'get'
---
apiVersion: v1
kind: Pod
metadata:
  name: e2e-conformance-test
  namespace: conformance
spec:
  containers:
  - name: conformance-container
    image: k8s.gcr.io/conformance-amd64:v1.18
    imagePullPolicy: IfNotPresent
    env:
    - name: E2E_FOCUS
      value: "root,0777,tmpfs"
    - name: E2E_SKIP
      value: ""
    - name: E2E_PROVIDER
      value: "skeleton"
    - name: E2E_PARALLEL
      value: "false"
    - name: E2E_VERBOSITY
      value: "4"
  restartPolicy: Never
  serviceAccountName: conformance-serviceaccount

```

**Environment**

Please include the following details of your environment: Fully custom-built, based on latest gVisor release.
