### ISSUE TITLE
Per sandbox flags

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#3494]
runsc flags can be set using docker runtime configuration and containerd runtime configuration (for K8s). Flags apply to all containers/pods spawned using that runtime, making it hard to run one off configurations for troubleshooting and testing.

We could use `specs.Spec.Annotations` to set flags for a single container that overrides any flag set in the runtime configuration. This is useful specially for K8s where the alternative is to either change node settings for all pods, or to create and configure an entire new runtime class. In K8s, pod annotations are passed in verbatim to the runtime.

Here is an example of a pod that wants to enable debug with runsc:

```yaml
metadata:
  annotations:
    dev.gvisor.flag.debug: "true"
    dev.gvisor.flag.debug-log: "/tmp/runsc/"
```

This can also be used to enable features:

```yaml
metadata:
  annotations:
    dev.gvisor.flag.vfs2: "true"
```
