### ISSUE TITLE
Duplicated environment variable passed to the process (from image and user input)

### ISSUE THREAD

**Issue by vdemeester** [google/gvisor#5226]
**Description**

In a kubernetes environment, with gvisor (enable through gke sandbox or configure through `containerd`), the environment variables set on pods are not set correctly, or at least are set *differently* from other runtime (`runc`, …).

In a gist, starting a container with an environment variable already present in the container configuration (in the issue linked below, `DOCKER_CONFIG`), `gvisor` gives to the underlying process both the image and the *user configured* environment variable. This is inconsistent compared to other runtime where the *user configured* one replace the one set in the image.

See https://github.com/tektoncd/pipeline/issues/3666 for more inputs (especially [here](https://github.com/tektoncd/pipeline/issues/3666#issuecomment-756745762)).

**Steps to reproduce**

On a kubernetes environment with `gvisor` enabled (here through a runtimeClass name `untrusted`), run the following : 

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-1
  name: test-1
  namespace: test
spec:
  containers:
  - command:
    - env
    image: gcr.io/kaniko-project/executor:debug
    #imagePullPolicy: Always
    name: test-1
    env:
    - name: DOCKER_CONFIG
      value: "/tekton/home/.docker"
    - name: TEST
      value: lol
  runtimeClassName: untrusted
  securityContext:
    runAsUser: 0
```

See the output containing two `DOCKER_CONFIG`. 

```
[…]
DOCKER_CONFIG=/kaniko/.docker/
DOCKER_CREDENTIAL_GCR_CONFIG=/kaniko/.config/gcloud/docker_credential_gcr_config.json
DOCKER_CONFIG=/tekton/home/.docker
[…]
```

Removing the `runtimeClassName` (aka running on cri-containerd, or cri-docker, …) produce the correct output (aka only one `DOCKER_CONFIG`, the one the user passed)

**Environment**

Please include the following details of your environment:

*   `runsc -version`

```
runsc version release-20201208.0
spec: 1.0.1-dev
```

*   `docker version` or `docker info` (if available)
*   `kubectl version` and `kubectl get nodes` (if using Kubernetes)

```
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-rc.0", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-15T00:59:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

*   `uname -a`
*   `git describe` (if built from source)
*   `runsc` debug logs (if available)
