### ISSUE TITLE
Secret generation with `/dev/urandom | fold -w 32 | head -n 1` never terminates

### ISSUE THREAD

**Issue by LFrobeen** [google/gvisor#5974]
**Description**

While trying to create a random secret based on `/dev/urandom` I noticed that the following command does not terminate when run in a gvisor environment: 
```cat /dev/urandom | fold -w 32 | head -n 1```
It does generate some output, but does not finish execution. 

When I run this command in a non-gvisor environment it terminates as expected after printing some random output.

**_Observed behavior:_**

```cat /dev/urandom | fold -w 32 | head -n 1``` prints random output but does not terminate when run with gvsior. 

Note that this is not limited to `/dev/urandom`, I am getting similar results with `/dev/zero`.

**_Expected behavior:_**

```cat /dev/urandom | fold -w 32 | head -n 1``` should terminate after printing some random output.

**Steps to reproduce**

I was able to reproduce the error in my kubernetes environment with this Pod manifest: 
```
kind: Pod
apiVersion: v1
metadata:
  name: test
  namespace: gvisor-debug
spec:
  runtimeClassName: gvisor
  restartPolicy: 'Never'
  containers:
    - name: main
      image: 'busybox:latest'
      command:
        - sh
        - -c
        - |
          cat /dev/urandom | fold -w 32 | head -n 1
          echo Done
          exit 0
      imagePullPolicy: Always
```

The pod prints some random output, but does not reach the `echo Done` command and never completes. 
When applying the manifest without the `runtimeClassName`, the Pod completes as expected.

**Environment**

`runsc -version`: 
```
runsc version google-363546579
spec: 1.0.1-dev
```

`kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

`kubectl get nodes`:
```
NAME                                                  STATUS   ROLES    AGE     VERSION
gke-gvisor-test-default-pool-53e288e7-19vx              Ready    <none>   26h    v1.19.9-gke.1900
gke-gvisor-test-e2-gvisor-ht-f1a5323c-0jwn              Ready    <none>   12h    v1.19.9-gke.1900
gke-gvisor-test-e2-gvisor-ht-5d7803db-dccg              Ready    <none>   3h1m   v1.19.9-gke.1900
gke-gvisor-test-e2-gvisor-ht-5d7803db-yhk4              Ready    <none>   124m   v1.19.9-gke.1900
gke-gvisor-test-e2-test-non-gvisor-5dca6907-vrh2        Ready    <none>   22h    v1.19.9-gke.1900
```

`uname -a`:
```Linux gke-gvisor-test-e2-gvisor-ht-f1a5323c-0jwn 5.4.89+ #1 SMP Sat Feb 13 19:45:14 PST 2021 x86_64 Intel(R) Xeon(R) CPU @ 2.00GHz GenuineIntel GNU/Linux```
