### ISSUE TITLE
GKE Sandbox (gVisor) inconsistent behavior

### ISSUE THREAD

**Issue by loganrobertclemons** [google/gvisor#8678]
### Description

This issue is being raised in conjunction with GCP Support ticket 43514787.

We've been observing some very strange behavior from GKE Sandbox + gVisor. gVisor appears to be intercepting system calls.

When you run a command like `ls` in the terminal of a Sandbox container, it intermittently shows the following message:

`[1]+ Stopped ls --color=auto`

This issue started popping up around late December or early January. A step by step guide for reproducing the issue is below, which might illustrate what is happening better.

### Steps to reproduce

1. Create a GKE cluster with a node pool running gvisor.
2. Create a deployment with `kubectl apply -f deployment.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gvisor-stopped-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gvisor-stopped-demo
  template:
    metadata:
      labels:
        name: gvisor-stopped-demo
    spec:
      runtimeClassName: gvisor
      containers:
      - image: node:18.12.1
        name: gvisor-stopped-demo
        command: ["sleep", "infinity"]
```
3. Copy the file pty.js (minor adaptation from the official example [here](https://github.com/microsoft/node-pty/blob/main/examples/fork/index.js)) into /root with `kubectl cp pty.js default/POD_NAME:/root`
```

var os = require('os');
var pty = require('node-pty');

var isWindows = os.platform() === 'win32';
var shell = isWindows ? 'powershell.exe' : 'bash';

var ptyProcess = pty.spawn(shell, [], {
  name: 'xterm-256color',
  cols: 80,
  rows: 26,
  cwd: isWindows ? process.env.USERPROFILE : process.env.HOME,
  env: process.env,
  useConpty: true
});

ptyProcess.onData(data => process.stdout.write(data));

ptyProcess.write(isWindows ? 'dir\r' : 'ls\r');

process.on('exit', () => ptyProcess.kill());

setTimeout(() => process.exit(), 4000);
```
4. Exec into the pod with `kubectl exec -it POD_NAME -- /bin/bash`
5. Change to root directory `cd /root`.
6. Install [node-pty ](https://github.com/microsoft/node-pty)with `npm i node-pty`.
7. Run the program with node pty.js.

The expected behavior is that it will print the files in the /root directory, wait a few seconds and then return:
```
# node pty.js
root@gvisor-stopped-demo-6665c79c9d-vgrx5:~# ls
node_modules  package-lock.json  package.json  pty.js
```

Instead, the ls process will intermittently be stopped:
```
root@gvisor-stopped-demo-6665c79c9d-vgrx5:~# ls

[1]   Stopped                 ls
```

This behavior is being seen from outside just running this pod. We have seen it intercepting system calls in multiple examples, such as the terminal running via Jupyter notebook as well as VS Code Server.

### kubectl (if using Kubernetes)

```shell
1.24.9-gke.3200
```
