### ISSUE TITLE
Segmentation fault when using powershell with GKE sandboxed nodes

### ISSUE THREAD

**Issue by jaym** [google/gvisor#9805]
### Description

When running some powershell shell scripts on GKE sandboxed nodes, powershell segfaults with the `xemu` provider that GKE uses. This behavior is consistent on multiple GKE node versions, the information provided below is from the rapid channel as of 12/11/2023. This does not happen with the `kvm`, `ptrace`, or `systrap` providers when run locally. I tested changing the GKE sandboxed node to use `systrap` and the segfault does not happen.

Attached the logs, not sure how helpful they are with the way I've run things. Let me know if you'd like me to get any more information.
[gvisorlogs.tar.gz](https://github.com/google/gvisor/files/13640659/gvisorlogs.tar.gz)

### Steps to reproduce

Here's a sample pod definition:
```
apiVersion: v1
kind: Pod
metadata:
    name: pwsh-test
    namespace: default
spec:
    automountServiceAccountToken: false
    containers:
    - args:
      - sleep 1d
      command:
      - sh
      - -c
      image: mcr.microsoft.com/powershell:latest
      imagePullPolicy: Always
      name: pwsh-test
      resources:
        limits:
          cpu: 1000m
          memory: 2000Mi
        requests:
          cpu: 1000m
          memory: 2000Mi
    nodeSelector:
      sandbox.gke.io/runtime: gvisor
    runtimeClassName: gvisor
    schedulerName: default-scheduler
    serviceAccount: default
    serviceAccountName: default
```

Get a shell into the pod:
```
kubectl exec -it pwsh-test -- /bin/sh
```

cat the following script into `test.ps`:
```
$ErrorActionPreference = "Stop"
Install-Module -Name MicrosoftTeams -Scope CurrentUser -Force
Import-Module MicrosoftTeams
echo "IM HERE 1"
Disconnect-MicrosoftTeams -Confirm:$false
echo "IM HERE 2"
```

run powershell:
```
pwsh -File test.ps
```

Here's a sample run:
```
# pwsh -File test.ps
IM HERE 1
IM HERE 2
Segmentation fault
```

From what I can tell, something about the command `Disconnect-MicrosoftTeams -Confirm:$false` triggers this behavior. It happens some time after `Disconnect-MicrosoftTeams -Confirm:$false`, so sometimes the second message does not get echoed.

### runsc version

```shell
# /home/containerd/usr/local/sbin/runsc --version
runsc version google-573904262
spec: 1.1.0-rc.2
```
```


### docker version (if using docker)

_No response_

### uname

Linux gke-jay-test-1-sandbox-d3f8bf14-qgmd 6.1.58+ #1 SMP PREEMPT_DYNAMIC Sat Nov  4 14:14:29 UTC 2023 x86_64 AMD EPYC 7B12 AuthenticAMD GNU/Linux

### kubectl (if using Kubernetes)

```shell
❯ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-gke.1203001
```

```
❯ kubectl get nodes
NAME                                        STATUS   ROLES    AGE   VERSION
gke-jay-test-1-default-pool-108d0347-bbl9   Ready    <none>   39m   v1.28.3-gke.1203001
gke-jay-test-1-sandbox-d3f8bf14-qgmd        Ready    <none>   30m   v1.28.3-gke.1203001
```
```


### repo state (if built from source)

_No response_

### runsc debug logs (if available)

_No response_
